apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: "/run/desktop/mnt/host/c/Users/mdgow/OneDrive/Desktop/Shreya M B/Cloud Computing/backupfiles"  # Path to your backup files directory on the host machine